version: '3'
services:

    web:
      image: phpdockerio/nginx:latest
      container_name: polycon-web
      volumes:
          - ./:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 89:80
      links:
          - php

    php:
        image: rvadym/sc-test:php7.1
        container_name: polycon-php
        volumes:
            - ./:/app
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
        links:
            - mysql
        depends_on:
            - mysql
        tty: true

    #-------------------------------------#

    mysql:
        image: mysql:5.7
        container_name: polycon-mysql
        environment:
          - MYSQL_ROOT_PASSWORD=123
          - MYSQL_DATABASE=symfony
          - MYSQL_USER=symfony
          - MYSQL_PASSWORD=123
        ports:
            - 3311:3306